app/urls.py
from django.urls import path
from . import views
from .views import generate_pdf


app_name = 'app'

urlpatterns = [
    path('', views.cover, name='cover'),
    path('title', views.title, name='title'),
    path('subtitle/', views.subtitle, name='subtitle'),
    path('boardtitle', views.boardtitle, name='boardtitle'),
    path('boardelement/', views.boardelement, name='boardelement'),
    path('preview/', views.preview, name='preview'),
    path('template/', views.template, name='template'),
    # path('download-pdf/', views.download_pdf, name='download_pdf'),
    # path('pdf/', MyPDFView.as_view(), name='download_pdf'),
    path('pdf/', generate_pdf, name='download_pdf'),
    # path('chart-image-upload/', ChartImageUploadView.as_view(), name='chart_image_upload'),

    path('chart/', views.chart, name='chart'),
    path('charts/', views.charts, name='charts'),

    path('preview1/', views.preview1, name='preview1'),
    path('generate_word/', views.generate_word, name='generate_word'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/boardelement.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="fr">
    <head>
        {% block title %}
            <title> GG </title>
        {% endblock title %}

		{% block meta %}
			<meta charset="UTF-8">
			<!-- mobile responsive meta -->
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        {% endblock meta %}


        {% block styles %}
			<!-- ** Plugins Needed for the Project ** -->
			<!-- Bootstrap -->
			<link rel="icon" href="{% static 'images/favicon.png' %}">
           
            <!-- CSS FILES START -->
            <link href="{% static 'css/custom.css' %}" rel="stylesheet">
            <link href="{% static 'css/color.css' %}" rel="stylesheet">
            <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
            <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
            <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/slick.css' %}" rel="stylesheet">
		{% endblock styles %}

		{% block stylepage %}

		{% endblock stylepage %}

	</head>

	<body>



        <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color: #4f94cd">
            <div class="container-fluid">
                <a class="navbar-brand" style="margin-right: 50px" href="#">PDF-GENERATOR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:cover' %}">Cover</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:title' %}">Titles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:subtitle' %}">SubTitles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:preview' %}">Preview</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:preview1' %}">Preview1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:template' %}">Template</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:boardtitle' %}">Board Title</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" style="font-weight: bold" aria-current="page" href="{% url 'app:boardelement' %}">Board Element</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>



        {% block content %}
        <div class="container">
            <div class="mb-4">
                <h2>Input Form</h2>
            </div>
            <form method="post" enctype="multipart/form-data" style="margin-bottom: 50px">
                {% csrf_token %}
                {% comment %} {{ form.as_p }} {% endcomment %}
                <div class="form-group">
                    {{form.media}}
                    {{form|crispy}}
                </div>
                <button type="submit" class="btn btn-success">Submit</button>
                <a href="{% url 'app:boardelement' %}" class="btn btn-primary">Add Another</a>
            </form>
        </div>
        {% endblock %}
    </body>
</html>

app/templates/boardtitle.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="fr">
    <head>
        {% block title %}
            <title> GG </title>
        {% endblock title %}

		{% block meta %}
			<meta charset="UTF-8">
			<!-- mobile responsive meta -->
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        {% endblock meta %}


        {% block styles %}
			<!-- ** Plugins Needed for the Project ** -->
			<!-- Bootstrap -->
			<link rel="icon" href="{% static 'images/favicon.png' %}">
           
            <!-- CSS FILES START -->
            <link href="{% static 'css/custom.css' %}" rel="stylesheet">
            <link href="{% static 'css/color.css' %}" rel="stylesheet">
            <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
            <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
            <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/slick.css' %}" rel="stylesheet">
		{% endblock styles %}

		{% block stylepage %}

		{% endblock stylepage %}

	</head>

	<body>



        <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color: #4f94cd">
            <div class="container-fluid">
                <a class="navbar-brand" style="margin-right: 50px" href="#">PDF-GENERATOR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:cover' %}">Cover</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:title' %}">Titles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:subtitle' %}">SubTitles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:preview' %}">Preview</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:preview1' %}">Preview1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:template' %}">Template</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" style="font-weight: bold" aria-current="page" href="{% url 'app:boardtitle' %}">Board Title</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:boardelement' %}">Board Element</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>



        {% block content %}
        <div class="container">
            <div class="mb-4">
                <h2>Input Form</h2>
            </div>
            <form method="post" enctype="multipart/form-data" style="margin-bottom: 50px">
                {% csrf_token %}
                {% comment %} {{ form.as_p }} {% endcomment %}
                <div class="form-group">
                    {{form.media}}
                    {{form|crispy}}
                </div>
                <button type="submit" class="btn btn-success">Submit</button>
                <a href="{% url 'app:boardtitle' %}" class="btn btn-primary">Add Another</a>
            </form>
        </div>
        {% endblock %}
    </body>
</html>

app/templates/cover.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="fr">
    <head>
        {% block title %}
            <title> GG </title>
        {% endblock title %}

		{% block meta %}
			<meta charset="UTF-8">
			<!-- mobile responsive meta -->
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        {% endblock meta %}

        {% block styles %}
			<!-- ** Plugins Needed for the Project ** -->
			<!-- Bootstrap -->
			<link rel="icon" href="{% static 'images/favicon.png' %}">
           
            <!-- CSS FILES START -->
            <link href="{% static 'css/custom.css' %}" rel="stylesheet">
            <link href="{% static 'css/color.css' %}" rel="stylesheet">
            <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
            <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
            <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/slick.css' %}" rel="stylesheet">
		{% endblock styles %}

		{% block stylepage %}

		{% endblock stylepage %}

	</head>

	<body>

        <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color: #4f94cd">
            <div class="container-fluid">
                <a class="navbar-brand" style="margin-right: 50px" href="#">PDF-GENERATOR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" style="font-weight: bold" aria-current="page" href="{% url 'app:cover' %}">Cover</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:title' %}">Titles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:subtitle' %}">SubTitles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:preview' %}">Preview</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:preview1' %}">Preview1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:template' %}">Template</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:boardtitle' %}">Board Title</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:boardelement' %}">Board Element</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block content %}
        <div class="container">
            <div class="mb-4">
                <h2>Input Form</h2>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% comment %} {{ form.as_p }} {% endcomment %}
                <div class="form-group">
                    {{form.media}}
                    {{form|crispy}}
                </div>
                <button type="submit" class="btn btn-success">Submit</button>
                {% comment %} <a href="{% url 'app:cover' %}" class="btn btn-primary">Add Another</a> {% endcomment %}
            </form>
        </div>
        {% endblock %}
    </body>
</html>

app/templates/subtitle.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="fr">
    <head>
        {% block title %}
            <title> GG </title>
        {% endblock title %}

		{% block meta %}
			<meta charset="UTF-8">
			<!-- mobile responsive meta -->
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        {% endblock meta %}


        {% block styles %}
			<!-- ** Plugins Needed for the Project ** -->
			<!-- Bootstrap -->
			<link rel="icon" href="{% static 'images/favicon.png' %}">
           
            <!-- CSS FILES START -->
            <link href="{% static 'css/custom.css' %}" rel="stylesheet">
            <link href="{% static 'css/color.css' %}" rel="stylesheet">
            <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
            <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
            <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/slick.css' %}" rel="stylesheet">
		{% endblock styles %}

		{% block stylepage %}

		{% endblock stylepage %}

	</head>

	<body>



        <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color: #4f94cd">
            <div class="container-fluid">
                <a class="navbar-brand" style="margin-right: 50px" href="#">PDF-GENERATOR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:cover' %}">Cover</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:title' %}">Titles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" style="font-weight: bold" aria-current="page" href="{% url 'app:subtitle' %}">SubTitles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:preview' %}">Preview</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:preview1' %}">Preview1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:template' %}">Template</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:boardtitle' %}">Board Title</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:boardelement' %}">Board Element</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>



        {% block content %}
        <div class="container">
            <div class="mb-4">
                <h2>Input Form</h2>
            </div>
            <form method="post" enctype="multipart/form-data" style="margin-bottom: 50px">
                {% csrf_token %}
                {% comment %} {{ form.as_p }} {% endcomment %}
                <div class="form-group">
                    {{form.media}}
                    {{form|crispy}}
                </div>
                <button type="submit" class="btn btn-success">Submit</button>
                <a href="{% url 'app:subtitle' %}" class="btn btn-primary">Add Another</a>
            </form>
        </div>
        {% endblock %}
    </body>
</html>

app/templates/template.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="fr">
    <head>
        {% block title %}
            <title> GG </title>
        {% endblock title %}

		{% block meta %}
			<meta charset="UTF-8">
			<!-- mobile responsive meta -->
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        {% endblock meta %}


        {% block styles %}
			<!-- ** Plugins Needed for the Project ** -->
			<!-- Bootstrap -->
			<link rel="icon" href="{% static 'images/favicon.png' %}">
           
            <!-- CSS FILES START -->
            <link href="{% static 'css/custom.css' %}" rel="stylesheet">
            <link href="{% static 'css/color.css' %}" rel="stylesheet">
            <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
            <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
            <link href="{% static 'css/lightbox.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/slick.css' %}" rel="stylesheet">

            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
            <link rel="stylesheet" href="assets/css/style.css">
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
		{% endblock styles %}

		{% block stylepage %}
        <style>
            
        </style>

		{% endblock stylepage %}

	</head>

	<body>



        <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color: #4f94cd">
            <div class="container-fluid">
                <a class="navbar-brand" style="margin-right: 50px" href="#">PDF-GENERATOR</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:cover' %}">Cover</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:title' %}">Titles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:subtitle' %}">SubTitles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:preview' %}">Preview</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:preview1' %}">Preview1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" style="font-weight: bold" aria-current="page" href="{% url 'app:template' %}">Template</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:boardtitle' %}">Board Title</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:boardelement' %}">Board Element</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>



        {% block content %}

        <div class="container">
          <div class="intro" style="margin-bottom: 50px">
              <h2 class="text-center">Templates</h2>
              <p class="text-center">Voir à quoi ressemble les templates de PDF disponible sur la plateforme</p>
          </div>
          <div class="row">
            <div class="col">
              <img src="{% static 'images/tmp2.png' %}" style="width: 500px">
              <h5 class="text-center">Template 1</h5>
            </div>
            <div class="col">
              <img src="{% static 'images/tmp1.png' %}" style="width: 500px">
              <h5 class="text-center">Template 2</h5>
            </div>
            <div class="w-100"></div>
            <div class="col"></div>
            <div class="col"></div>
          </div>
        </div>

        {% endblock %}
        <script src="{% static 'js/jquery.min.js' %}">
        <script src="{% static 'js/bootstrap.bundle.min.js' %}">
        <script src="{% static 'js/bootstrap.bundle.min.js' %}">
        <script src="{% static 'js/lightbox.min.js' %}">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox.min.js"></script>
    </body>
</html>

app/templates/title.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="fr">
    <head>
        {% block title %}
            <title> GG </title>
        {% endblock title %}

		{% block meta %}
			<meta charset="UTF-8">
			<!-- mobile responsive meta -->
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        {% endblock meta %}


        {% block styles %}
			<!-- ** Plugins Needed for the Project ** -->
			<!-- Bootstrap -->
			<link rel="icon" href="{% static 'images/favicon.png' %}">
           
            <!-- CSS FILES START -->
            <link href="{% static 'css/custom.css' %}" rel="stylesheet">
            <link href="{% static 'css/color.css' %}" rel="stylesheet">
            <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
            <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
            <link href="{% static 'css/all.min.css' %}" rel="stylesheet">
            <link href="{% static 'css/slick.css' %}" rel="stylesheet">
		{% endblock styles %}

		{% block stylepage %}

		{% endblock stylepage %}

	</head>

	<body>



        <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color: #4f94cd">
            <div class="container-fluid">
                <a class="navbar-brand" style="margin-right: 50px" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:cover' %}">Cover</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" style="font-weight: bold" aria-current="page" href="{% url 'app:title' %}">Titles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:subtitle' %}">SubTitles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:preview' %}">Preview</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:preview1' %}">Preview1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:template' %}">Template</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:boardtitle' %}">Board Title</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="font-weight: bold" aria-current="page" href="{% url 'app:boardelement' %}">Board Element</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>



        {% block content %}
        <div class="container">
            <div class="mb-4">
                <h2>Input Form</h2>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% comment %} {{ form.as_p }} {% endcomment %}
                <div class="form-group">
                    {{form.media}}
                    {{form|crispy}}
                </div>
                <button type="submit" class="btn btn-success">Submit</button>
                <a href="{% url 'app:title' %}" class="btn btn-primary">Add Another</a>
            </form>
        </div>
        {% endblock %}
    </body>
</html>